export const TodosActions = {
	TODOS_ADD_TODO: 'TODOS_ADD_TODO',
	TODOS_EDIT_TODO: 'TODOS_EDIT_TODO',
	TODOS_DELETE_TODO: 'TODOS_DELETE_TODO',
	TODOS_DELETE_ALL_TODOS: 'TODOS_DELETE_ALL_TODOS',
	TODOS_TOGGLE_TODO: 'TODOS_TOGGLE_TODO',
	TODOS_TOGGLE_ALL_TODOS: 'TODOS_TOGGLE_ALL_TODOS'
};